### ISSUE TITLE
Rucio download with st.is_stored results in partial downloads

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#586]
**Describe the bug**
st.is_stored and downloading using rucio is an previously untested edge case.

**To Reproduce**
Insert the MWE of how to reproduce the error
```python
st = straxen.contexts.xenonnt(cmt_version='global_v3', use_rucio=True, output_folder = './rucio_staging_dir3')
run_id = '024345'
print(st.is_stored(run, 'pulse_counts'))

pc = st.get_array(run, 'pulse_counts')
print(pc.nbytes)
```
Which yields
```
Downloading xnt_024345:pulse_counts-niuq6un3aa-metadata.json

TrueException in thread CRITICAL:ThreadedMailboxProcessor:Target Mailbox (pulse_counts) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7f47f3d21740>)
load:pulse_counts:
Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/mailbox.py", line 267, in _send_from
    self.kill_from_exception(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/mailbox.py", line 186, in kill_from_exception
    raise e
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/mailbox.py", line 254, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/storage/common.py", line 456, in loader
    yield self._read_and_format_chunk(**read_chunk_kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/storage/common.py", line 474, in _read_and_format_chunk
    data = self._read_chunk(backend_key,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/storage/files.py", line 232, in _read_chunk
    return strax.load_file(fn, dtype=dtype, compressor=compressor)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/io.py", line 42, in load_file
    with open(f, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './rucio_staging_dir3/024345-pulse_counts-niuq6un3aa/pulse_counts-niuq6un3aa-000000'
```

**Expected behavior**
Either not download the metadata or download all at next data-request

**Screenshots**

**Versions**
Please add the output of:
```
Working on midway2-0417.rcc.local with the following versions and installation paths:
python	v3.8.10	(default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
strax	v0.16.0	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax
straxen	v0.19.2	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/straxen
cutax	v0.1.0	/dali/lgrandi/strax/cutax/cutax

```

**Comment by JoranAngevaare** [comment]
Fixed in #688 #694
