### ISSUE TITLE
strax.chunk.CannotSplit error

### ISSUE THREAD

**Issue by ershockley** [XENONnT/straxen#600]
**Describe the bug**
I'm seeing an error like below during reprocessing of some data. It looks like the error occurs in `merged_s2s`. 

```
Exception in thread build:merged_s2s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/context.py", line 1215, in make
    for _ in self.get_iter(run_ids[0], targets,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/context.py", line 1099, in get_iter
    generator.throw(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/context.py", line 1072, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/processor.py", line 286, in iter
    raise exc.with_traceback(traceback)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/mailbox.py", line 255, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/plugin.py", line 616, in iter
    yield from super().iter(iters, executor=executor)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/plugin.py", line 427, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/plugin.py", line 636, in do_compute
    _, result = result.split(t=self.sent_until,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/chunk.py", line 170, in split
    data1, data2, t = split_array(
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax/chunk.py", line 376, in split_array
    raise CannotSplit()
strax.chunk.CannotSplit
```

**To Reproduce**
Enter the `latest` container on Midway and try making, e.g., `event_info_double` for Run 23413:
```
st = straxen.contexts.xenonnt(<latest cmt global version>)
st.make('023413', 'event_info_double')
```

I also saw this error for Run 20318. 

**Versions**

```
>>> straxen.print_versions()
Working on midway2-0413.rcc.local with the following versions and installation paths:
python  v3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
strax   v0.16.1 /opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax
straxen v0.19.3 /opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/straxen
```

**Comment by WenzDaniel** [comment]
Duplication with https://github.com/AxFoundation/strax/issues/490
