### ISSUE TITLE
event_basics ended prematurely

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#633]
**Describe the bug**
Event_bascics fails, it appears to somehow miss data in the last chunk?

**To Reproduce**
process run 26366 25763 or 25267 

**Versions**
```
cutax is not installed
Working on eb0.xenon.local with the following versions and installation paths:
python	v3.8.5	(default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
strax	v0.16.1	/home/xedaq/software/strax/strax
straxen	v0.19.3	/home/xedaq/software/straxen/straxen
```

**Traceback**

```
Exception info: Traceback (most recent call last):
  File "/home/xedaq/software/strax/strax/plugin.py", line 301, in _fetch_chunk
    [self.input_buffer[d], next(iters[d])])
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1293, in run_strax
    st_make()
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1271, in st_make
    st.make(run_id, targets,
  File "/home/xedaq/software/strax/strax/context.py", line 1215, in make
    for _ in self.get_iter(run_ids[0], targets,
  File "/home/xedaq/software/strax/strax/context.py", line 1099, in get_iter
    generator.throw(e)
  File "/home/xedaq/software/strax/strax/context.py", line 1072, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/home/xedaq/software/strax/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/home/xedaq/software/strax/strax/processor.py", line 286, in iter
    raise exc.with_traceback(traceback)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 255, in _send_from
    x = next(iterable)
  File "/home/xedaq/software/strax/strax/plugin.py", line 380, in iter
    self._fetch_chunk(
  File "/home/xedaq/software/strax/strax/plugin.py", line 309, in _fetch_chunk
    raise RuntimeError(
RuntimeError: Tried to get data until 1628453967070352277, but event_basics ended prematurely at 1628453946297691160
```

**Comment by jorana** [comment]
cannot reproduce
