### ISSUE TITLE
events_nv insufficient buffer

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#765]
**Describe the bug**
we are getting the following error on the eventbuilding of 032540

```
Exception in thread build:events_nv:
Target Mailbox (events_nv) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'AssertionError'>, AssertionError('Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.'), <traceback o
bject at 0x7f2f052d8940>)
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/xedaq/software/npshmex/npshmex.py", line 193, in shm_wrap_f
    result = f(*args, **kwargs)
  File "/home/xedaq/software/strax/strax/plugin.py", line 525, in do_compute
    result = self.compute(**kwargs)
  File "/home/xedaq/software/straxen/straxen/plugins/veto_hitlets.py", line 141, in compute
    strax.hitlet_properties(temp_hitlets)
  File "/home/xedaq/software/strax/strax/processing/statistics.py", line 92, in highest_density_region
    assert len(gaps) < _buffer_size, mes
AssertionError: Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread discard_lone_raw_records_nv:
Exception in thread discard_lone_raw_record_statistics_nv:
Traceback (most recent call last):
    self.run()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 294, in _send_from
    self.run()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self.kill_from_exception(e)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 213, in kill_from_exception
    self._target(*self._args, **self._kwargs)
    raise e
  File "/home/xedaq/software/strax/strax/processor.py", line 220, in discarder
  File "/home/xedaq/software/strax/strax/mailbox.py", line 281, in _send_from
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/software/strax/strax/processor.py", line 220, in discarder
    for _ in source:
    x = next(iterable)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 394, in _read
  File "/home/xedaq/software/strax/strax/plugin.py", line 616, in iter
    for _ in source:
  File "/home/xedaq/software/strax/strax/mailbox.py", line 394, in _read
    yield from super().iter(iters, executor=executor)
    raise MailboxKilled(self.killed_because)
  File "/home/xedaq/software/strax/strax/plugin.py", line 369, in iter
strax.mailbox.MailboxKilled: (<class 'AssertionError'>, AssertionError('Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.'), <traceback object at 0x7f2f052d8940>)
    raise MailboxKilled(self.killed_because)
    if not self._fetch_chunk(pacemaker, iters):
strax.mailbox.MailboxKilled: (<class 'AssertionError'>, AssertionError('Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.'), <traceback object at 0x7f2f052d8940>)
  File "/home/xedaq/software/strax/strax/plugin.py", line 301, in _fetch_chunk
    [self.input_buffer[d], next(iters[d])])
  File "/home/xedaq/software/strax/strax/mailbox.py", line 432, in _read
    res = msg.result(timeout=self.timeout)
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/xedaq/software/strax/strax/storage/common.py", line 646, in save_from
    source.throw(e)
  File "/home/xedaq/software/strax/strax/storage/common.py", line 608, in save_from
    next_chunk = next(source)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 432, in _read
    res = msg.result(timeout=self.timeout)
Exception in thread save_0:hitlets_nv:
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 439, in result
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/xedaq/software/npshmex/npshmex.py", line 193, in shm_wrap_f
    result = f(*args, **kwargs)
  File "/home/xedaq/software/strax/strax/plugin.py", line 525, in do_compute
    result = self.compute(**kwargs)
  File "/home/xedaq/software/straxen/straxen/plugins/veto_hitlets.py", line 141, in compute
    strax.hitlet_properties(temp_hitlets)
  File "/home/xedaq/software/strax/strax/processing/statistics.py", line 92, in highest_density_region
    assert len(gaps) < _buffer_size, mes
AssertionError: Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.
"""
    return self.__get_result()

The above exception was the direct cause of the following exception:

  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise self._exception
AssertionError: Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.
    self.run()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/software/strax/strax/storage/common.py", line 646, in save_from
    source.throw(e)
  File "/home/xedaq/software/strax/strax/storage/common.py", line 608, in save_from
    next_chunk = next(source)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 432, in _read
    res = msg.result(timeout=self.timeout)
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
AssertionError: Found more intervals than "_buffer_size" allows pleaseincrease the size of the buffer.
```

**To Reproduce**
Process 032540 events_nv

**Expected behavior**
work

**Versions**
Please add the output of:
```
(py38) xedaq@eb1:~/joran$ python -c "import straxen ; straxen.print_versions()"
cutax is not installed
Working on eb1.xenon.local with the following versions and installation paths:
python  v3.8.5  (default, Aug  5 2020, 08:36:46) [GCC 7.3.0]
strax   v1.1.1  /home/xedaq/software/strax/strax        git branch:master | 1f4d22e
straxen v1.1.2  /home/xedaq/software/straxen/straxen    git branch:master | 63a1561
```

**Comment by WenzDaniel** [comment]
Should be solved with https://github.com/AxFoundation/strax/pull/591
