### ISSUE TITLE
`veto_intervals` reports an error for `039466`

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#979]
**Describe the bug**
```
Host midway2-0421.rcc.local
 module version                                                                             path  git
 python  3.8.12                          /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/bin/python None
straxen   1.6.0 /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen None
  strax   1.2.0   /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax None
  cutax   1.6.0                                /dali/lgrandi/xenonnt/software/cutax/latest/cutax None
Removing data in ./strax_data/039466-veto_intervals-s7g2tgs7q5 to overwrite
Traceback (most recent call last):
  File "/home/angevaare/software/straxen/bin/straxer", line 323, in <module>
    sys.exit(main(args))
  File "/home/angevaare/software/straxen/bin/straxer", line 289, in main
    run_make(target)
  File "/home/angevaare/software/straxen/bin/straxer", line 258, in run_make
    for i, d in enumerate(get_results()):
  File "/home/angevaare/software/straxen/bin/straxer", line 255, in get_results
    yield from st.get_iter(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/context.py", line 1300, in get_iter
    generator.throw(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/context.py", line 1272, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/processor.py", line 302, in iter
    raise exc.with_traceback(traceback)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 658, in iter
    yield from super().iter(iters, executor=executor)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 459, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 675, in do_compute
    result = super().do_compute(chunk_i=chunk_i, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 567, in do_compute
    result = self.compute(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen/plugins/acqmon_processing.py", line 204, in compute
    veto_hits_start, veto_hits_stop = self.handle_starts_and_stops_outside_of_run(
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen/plugins/acqmon_processing.py", line 284, in handle_starts_and_stops_outside_of_run
    raise ValueError(message)
ValueError: Got inconsistent number of busy_ starts 106996) / stops (106988). Despite the fact that we inserted one extra stop at the end of the run.
```

**Comment by JoranAngevaare** [comment]
Another but not dissimilar issue in `021351`

I wouldn't be surprised if the chunking is really affecting us and we just need something like https://github.com/AxFoundation/strax/pull/654
```
ValueError: Found veto's starting before the previous stopped
Host midway2-0422.rcc.local
 module version                                                                             path  git
 python  3.8.12                          /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/bin/python None
  cutax   1.6.0                                /dali/lgrandi/xenonnt/software/cutax/latest/cutax None
straxen   1.6.0 /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen None
  strax   1.2.0   /opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax None
Removing data in ./strax_data/021351-veto_intervals-s7g2tgs7q5 to overwrite
Traceback (most recent call last):
  File "/home/angevaare/software/straxen/bin/straxer", line 323, in <module>
    sys.exit(main(args))
  File "/home/angevaare/software/straxen/bin/straxer", line 289, in main
    run_make(target)
  File "/home/angevaare/software/straxen/bin/straxer", line 258, in run_make
    for i, d in enumerate(get_results()):
  File "/home/angevaare/software/straxen/bin/straxer", line 255, in get_results
    yield from st.get_iter(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/context.py", line 1300, in get_iter
    generator.throw(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/context.py", line 1272, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/processor.py", line 302, in iter
    raise exc.with_traceback(traceback)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 658, in iter
    yield from super().iter(iters, executor=executor)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 459, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 675, in do_compute
    result = super().do_compute(chunk_i=chunk_i, **kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/strax/plugin.py", line 567, in do_compute
    result = self.compute(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen/plugins/acqmon_processing.py", line 204, in compute
    veto_hits_start, veto_hits_stop = self.handle_starts_and_stops_outside_of_run(
  File "/opt/XENONnT/anaconda/envs/XENONnT_2022.03.5/lib/python3.8/site-packages/straxen/plugins/acqmon_processing.py", line 287, in handle_starts_and_stops_outside_of_run
    raise ValueError('Found veto\'s starting before the previous stopped')
ValueError: Found veto's starting before the previous stopped
Processing job ended
```
